# Global Acosix Audit Logger
logger.acosixAudit.name = de.acosix.alfresco.audit.repo
logger.acosixAudit.level = INFO

# Specific Loggers (INFO)
logger.acosixPersonAudit.name = de.acosix.alfresco.audit.repo.batch.PersonAuditWorker
logger.acosixPersonAudit.level = INFO

logger.acosixAuditUserGet.name = de.acosix.alfresco.audit.repo.web.scripts.AuditUserGet
logger.acosixAuditUserGet.level = INFO

logger.acosixAuditAuth.name = de.acosix.alfresco.audit.repo.web.auth.AuthenticationAuditingListener
logger.acosixAuditAuth.level = INFO

logger.acosixConsolidateJob.name = de.acosix.alfresco.audit.repo.job.ConsolidateActiveUsersAuditJob
logger.acosixConsolidateJob.level = INFO

logger.acosixPropDouble.name = de.acosix.alfresco.audit.repo.job.PropertyDoubleValuesCleanupJob
logger.acosixPropDouble.level = INFO

logger.acosixPropString.name = de.acosix.alfresco.audit.repo.job.PropertyStringValuesCleanupJob
logger.acosixPropString.level = INFO

logger.acosixPropSerial.name = de.acosix.alfresco.audit.repo.job.PropertySerializableValuesCleanupJob
logger.acosixPropSerial.level = INFO

logger.acosixPropValues.name = de.acosix.alfresco.audit.repo.job.PropertyValuesCleanupJob
logger.acosixPropValues.level = INFO

logger.acosixPropRoot.name = de.acosix.alfresco.audit.repo.job.PropertyRootCleanupJob
logger.acosixPropRoot.level = INFO

# Chatty Batch Processors (WARN)
logger.acosixAuditUserGetBatch.name = de.acosix.alfresco.audit.repo.web.scripts.AuditUserGet.batchProcessor
logger.acosixAuditUserGetBatch.level = WARN

logger.acosixConsolidateJobBatch.name = de.acosix.alfresco.audit.repo.job.ConsolidateActiveUsersAuditJob.batchProcessor
logger.acosixConsolidateJobBatch.level = WARN

logger.acosixPropDoubleBatch.name = de.acosix.alfresco.audit.repo.job.PropertyDoubleValuesCleanupJob.batchProcessor
logger.acosixPropDoubleBatch.level = WARN

logger.acosixPropStringBatch.name = de.acosix.alfresco.audit.repo.job.PropertyStringValuesCleanupJob.batchProcessor
logger.acosixPropStringBatch.level = WARN

logger.acosixPropSerialBatch.name = de.acosix.alfresco.audit.repo.job.PropertySerializableValuesCleanupJob.batchProcessor
logger.acosixPropSerialBatch.level = WARN

logger.acosixPropValuesBatch.name = de.acosix.alfresco.audit.repo.job.PropertyValuesCleanupJob.batchProcessor
logger.acosixPropValuesBatch.level = WARN

logger.acosixPropRootBatch.name = de.acosix.alfresco.audit.repo.job.PropertyRootCleanupJob.batchProcessor
logger.acosixPropRootBatch.level = WARN