logger.acosix-alfresco-audit.name = de.acosix.alfresco.audit.repo
logger.acosix-alfresco-audit.level = INFO

logger.acosix-alfresco-audit-personAuditWorker.name = de.acosix.alfresco.audit.repo.batch.PersonAuditWorker
logger.acosix-alfresco-audit-personAuditWorker.level = INFO

logger.acosix-alfresco-audit-userGet.name = de.acosix.alfresco.audit.repo.web.scripts.AuditUserGet
logger.acosix-alfresco-audit-userGet.level = INFO

logger.acosix-alfresco-audit-authListener.name = de.acosix.alfresco.audit.repo.web.auth.AuthenticationAuditingListener
logger.acosix-alfresco-audit-authListener.level = INFO

logger.acosix-alfresco-audit-consolidateUserJob.name = de.acosix.alfresco.audit.repo.job.ConsolidateActiveUsersAuditJob
logger.acosix-alfresco-audit-consolidateUserJob.level = INFO

logger.acosix-alfresco-audit-propDoubleJob.name = de.acosix.alfresco.audit.repo.job.PropertyDoubleValuesCleanupJob
logger.acosix-alfresco-audit-propDoubleJob.level = INFO

logger.acosix-alfresco-audit-propStringJob.name = de.acosix.alfresco.audit.repo.job.PropertyStringValuesCleanupJob
logger.acosix-alfresco-audit-propStringJob.level = INFO

logger.acosix-alfresco-audit-propBlobJob.name = de.acosix.alfresco.audit.repo.job.PropertySerializableValuesCleanupJob
logger.acosix-alfresco-audit-propBlobJob.level = INFO

logger.acosix-alfresco-audit-propValuesJob.name = de.acosix.alfresco.audit.repo.job.PropertyValuesCleanupJob
logger.acosix-alfresco-audit-propValuesJob.level = INFO

logger.acosix-alfresco-audit-propRootJob.name = de.acosix.alfresco.audit.repo.job.PropertyRootCleanupJob
logger.acosix-alfresco-audit-propRootJob.level = INFO

logger.acosix-alfresco-audit-userGet-processor.name = de.acosix.alfresco.audit.repo.web.scripts.AuditUserGet.batchProcessor
logger.acosix-alfresco-audit-userGet-processor.level = WARN

logger.acosix-alfresco-audit-consolidateUserJob-processor.name = de.acosix.alfresco.audit.repo.job.ConsolidateActiveUsersAuditJob.batchProcessor
logger.acosix-alfresco-audit-consolidateUserJob-processor.level = WARN

logger.acosix-alfresco-audit-propDoubleJob-processor.name = de.acosix.alfresco.audit.repo.job.PropertyDoubleValuesCleanupJob.batchProcessor
logger.acosix-alfresco-audit-propDoubleJob-processor.level = WARN

logger.acosix-alfresco-audit-propStringJob-processor.name = de.acosix.alfresco.audit.repo.job.PropertyStringValuesCleanupJob.batchProcessor
logger.acosix-alfresco-audit-propStringJob-processor.level = WARN

logger.acosix-alfresco-audit-propBlobJob-processor.name = de.acosix.alfresco.audit.repo.job.PropertySerializableValuesCleanupJob.batchProcessor
logger.acosix-alfresco-audit-propBlobJob-processor.level = WARN

logger.acosix-alfresco-audit-propValuesJob-processor.name = de.acosix.alfresco.audit.repo.job.PropertyValuesCleanupJob.batchProcessor
logger.acosix-alfresco-audit-propValuesJob-processor.level = WARN

logger.acosix-alfresco-audit-propRootJob-processor.name = de.acosix.alfresco.audit.repo.job.PropertyRootCleanupJob.batchProcessor
logger.acosix-alfresco-audit-propRootJob-processor.level = WARN